site_name: Tools for Equitable and Efficient Collaborations

theme:
   name: material

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
